export const gConstants = {
    API_ROOT: 'http://192.168.1.30:10010',
    SERVER_ROOT: 'http://localhost',

    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',
    INFO: 'ALERT_INFO',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',


    RESET_REQUEST: 'USERS_RESET_REQUEST',
    RESET_SUCCESS: 'USERS_RESET_SUCCESS',
    RESET_FAILURE: 'USERS_RESET_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    // ********* DATA ************
    GET_DATA_REQUEST: 'GET_DATA_REQUEST',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    GET_DATA_FAILURE: 'GET_DATA_FAILURE',

    ADD_DATA_REQUEST: 'ADD_DATA_REQUEST',
    ADD_DATA_SUCCESS: 'ADD_DATA_SUCCESS',
    ADD_DATA_FAILURE: 'ADD_DATA_FAILURE',

    DELETE_DATA_REQUEST: 'DELETE_DATA_REQUEST',
    DELETE_DATA_SUCCESS: 'DELETE_DATA_SUCCESS',
    DELETE_DATA_FAILURE: 'DELETE_DATA_FAILURE',
    // ****************************

    // ********* ASSETS ************
    GET_ASSET_REQUEST: 'GET_ASSET_REQUEST',
    GET_ASSET_SUCCESS: 'GET_ASSET_SUCCESS',
    GET_ASSET_FAILURE: 'GET_ASSET_FAILURE',

    ADD_ASSET_REQUEST: 'ADD_ASSET_REQUEST',
    ADD_ASSET_SUCCESS: 'ADD_ASSET_SUCCESS',
    ADD_ASSET_FAILURE: 'ADD_ASSET_FAILURE',

    DELETE_ASSET_REQUEST: 'DELETE_ASSET_REQUEST',
    DELETE_ASSET_SUCCESS: 'DELETE_ASSET_SUCCESS',
    DELETE_ASSET_FAILURE: 'DELETE_ASSET_FAILURE',
    // ****************************

    // ********* DEVICE ************
    GET_DEVICE_REQUEST: 'GET_DEVICE_REQUEST',
    GET_DEVICE_SUCCESS: 'GET_DEVICE_SUCCESS',
    GET_DEVICE_FAILURE: 'GET_DEVICE_FAILURE',

    ADD_DEVICE_REQUEST: 'ADD_DEVICE_REQUEST',
    ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
    ADD_DEVICE_FAILURE: 'ADD_DEVICE_FAILURE',

    DELETE_DEVICE_REQUEST: 'DELETE_DEVICE_REQUEST',
    DELETE_DEVICE_SUCCESS: 'DELETE_DEVICE_SUCCESS',
    DELETE_DEVICE_FAILURE: 'DELETE_DEVICE_FAILURE',
    // ****************************

    // ********* DASHBOARD ************
    GET_DASHBOARD_REQUEST: 'GET_DASHBOARD_REQUEST',
    GET_DASHBOARD_SUCCESS: 'GET_DASHBOARD_SUCCESS',
    GET_DASHBOARD_FAILURE: 'GET_DASHBOARD_FAILURE',

    ADD_DASHBOARD_REQUEST: 'ADD_DASHBOARD_REQUEST',
    ADD_DASHBOARD_SUCCESS: 'ADD_DASHBOARD_SUCCESS',
    ADD_DASHBOARD_FAILURE: 'ADD_DASHBOARD_FAILURE',

    UPDATE_DASHBOARD_REQUEST: 'UPDATE_DASHBOARD_REQUEST',
    UPDATE_DASHBOARD_SUCCESS: 'UPDATE_DASHBOARD_SUCCESS',
    UPDATE_DASHBOARD_FAILURE: 'UPDATE_DASHBOARD_FAILURE',

    DELETE_DASHBOARD_REQUEST: 'DELETE_DASHBOARD_REQUEST',
    DELETE_DASHBOARD_SUCCESS: 'DELETE_DASHBOARD_SUCCESS',
    DELETE_DASHBOARD_FAILURE: 'DELETE_DASHBOARD_FAILURE',


    // ****************************

    // ********* VARIABLE ************
    GET_VARIABLE_REQUEST: 'GET_VARIABLE_REQUEST',
    GET_VARIABLE_SUCCESS: 'GET_VARIABLE_SUCCESS',
    GET_VARIABLE_FAILURE: 'GET_VARIABLE_FAILURE',

    ADD_VARIABLE_REQUEST: 'ADD_VARIABLE_REQUEST',
    ADD_VARIABLE_SUCCESS: 'ADD_VARIABLE_SUCCESS',
    ADD_VARIABLE_FAILURE: 'ADD_VARIABLE_FAILURE',

    DELETE_VARIABLE_REQUEST: 'DELETE_VARIABLE_REQUEST',
    DELETE_VARIABLE_SUCCESS: 'DELETE_VARIABLE_SUCCESS',
    DELETE_VARIABLE_FAILURE: 'DELETE_VARIABLE_FAILURE',
    // ****************************

    // ********* PARAMETER ************
    GET_PARAMETER_REQUEST: 'GET_PARAMETER_REQUEST',
    GET_PARAMETER_SUCCESS: 'GET_PARAMETER_SUCCESS',
    GET_PARAMETER_FAILURE: 'GET_PARAMETER_FAILURE',

    ADD_PARAMETER_REQUEST: 'ADD_PARAMETER_REQUEST',
    ADD_PARAMETER_SUCCESS: 'ADD_PARAMETER_SUCCESS',
    ADD_PARAMETER_FAILURE: 'ADD_PARAMETER_FAILURE',

    DELETE_PARAMETER_REQUEST: 'DELETE_PARAMETER_REQUEST',
    DELETE_PARAMETER_SUCCESS: 'DELETE_PARAMETER_SUCCESS',
    DELETE_PARAMETER_FAILURE: 'DELETE_PARAMETER_FAILURE',
    // ****************************
};
